# Generated by Django 6.0.3 on 2026-04-05 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wire_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('rm_name', models.CharField(db_index=True, max_length=255)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('rm_manager_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('ma_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager_id', models.ForeignKey(blank=True, db_column='manager_id', help_text='Manager this employee reports to (self-join hierarchy via numeric ID)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='core.employee')),
            ],
            options={
                'db_table': 'employee_dimension',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('client_name', models.CharField(db_index=True, max_length=255)),
                ('rm_name', models.CharField(db_index=True, max_length=255)),
                ('rm_manager_name', models.CharField(blank=True, max_length=255, null=True)),
                ('client_type', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, db_column='employee_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='core.employee')),
            ],
            options={
                'db_table': 'client_dimension',
            },
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rm_manager_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('rm_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('ma_name', models.CharField(blank=True, max_length=255, null=True)),
                ('wire_code', models.CharField(blank=True, max_length=50, null=True)),
                ('client_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('total_brokerage', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=15)),
                ('cash_delivery', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cash_intraday', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('equity_cash_delivery_turnover', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('equity_futures_turnover', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('equity_options_turnover', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('equity_cash_intraday_turnover', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_equity_cash_turnover', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_equity_fno_turnover', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_equity_turnover', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_turnover', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('mf_brokerage', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('mf_turnover', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('data_source', models.CharField(choices=[('BROKERAGE', 'Brokerage Fact'), ('MF', 'Mutual Fund Fact')], default='BROKERAGE', max_length=50)),
                ('period', models.CharField(blank=True, max_length=20, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('loaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_records', to='core.client')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_records', to='core.employee')),
            ],
            options={
                'db_table': 'sales_record',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('L', 'Leader'), ('M', 'Manager'), ('R', 'RM / MA')], default='R', max_length=1)),
                ('wire_code', models.CharField(blank=True, db_index=True, help_text='Wire/Employee code for matching with data', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='User can login if True')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(blank=True, help_text='Link to Employee dimension (RM master data)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='core.employee')),
                ('reporting_to', models.ForeignKey(blank=True, help_text='Manager this user reports to (creates hierarchy)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='core.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['rm_name'], name='employee_di_rm_name_1a9ba6_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['manager_id'], name='employee_di_manager_49e3d9_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['email'], name='employee_di_email_cfcafc_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['is_active'], name='employee_di_is_acti_e52ceb_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['client_name'], name='client_dime_client__5a2269_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['rm_name'], name='client_dime_rm_name_33a8ae_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['employee'], name='client_dime_employe_5793b8_idx'),
        ),
        migrations.AddIndex(
            model_name='salesrecord',
            index=models.Index(fields=['rm_name', 'total_brokerage'], name='sales_recor_rm_name_5e7b2e_idx'),
        ),
        migrations.AddIndex(
            model_name='salesrecord',
            index=models.Index(fields=['client_name', 'rm_name'], name='sales_recor_client__c821d9_idx'),
        ),
        migrations.AddIndex(
            model_name='salesrecord',
            index=models.Index(fields=['period', 'data_source'], name='sales_recor_period_534cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['wire_code'], name='user_profil_wire_co_5cb1c8_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role'], name='user_profil_role_c7e6f1_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['reporting_to'], name='user_profil_reporti_5ca4a2_idx'),
        ),
    ]
