# Generated by Django 5.0.4 on 2025-12-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_salesrecord_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesrecord',
            name='brokerage_equity',
        ),
        migrations.RemoveField(
            model_name='salesrecord',
            name='brokerage_mf',
        ),
        migrations.RemoveField(
            model_name='salesrecord',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='salesrecord',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='salesrecord',
            name='relationship_manager',
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='cash_delivery',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='cash_intraday',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='equity_cash_delivery_turnover',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='equity_cash_intraday_turnover',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='equity_futures_turnover',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='equity_options_turnover',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='ma_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='rm_manager_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='rm_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='total_brokerage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='total_equity_cash_turnover',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='total_equity_fno_turnover',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='total_equity_turnover',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='total_turnover',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='wire_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
