# Generated by Django 5.2.7 on 2026-02-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_employee_hierarchy_userprofile'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employee',
            name='employee_dimension_rm_manager_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='employee_dimension_ma_name_idx',
        ),
        migrations.RenameIndex(
            model_name='client',
            new_name='client_dime_client__5a2269_idx',
            old_name='client_dimension_client_name_idx',
        ),
        migrations.RenameIndex(
            model_name='client',
            new_name='client_dime_rm_name_33a8ae_idx',
            old_name='client_dimension_rm_name_idx',
        ),
        migrations.RenameIndex(
            model_name='client',
            new_name='client_dime_wire_co_bf3abe_idx',
            old_name='client_dimension_wire_code_idx',
        ),
        migrations.RenameIndex(
            model_name='employee',
            new_name='employee_di_rm_name_1a9ba6_idx',
            old_name='employee_dimension_rm_name_idx',
        ),
        migrations.RenameIndex(
            model_name='employee',
            new_name='employee_di_manager_49e3d9_idx',
            old_name='employee_dimension_manager_idx',
        ),
        migrations.RenameIndex(
            model_name='employee',
            new_name='employee_di_is_acti_e52ceb_idx',
            old_name='employee_dimension_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='salesrecord',
            new_name='sales_recor_rm_name_5e7b2e_idx',
            old_name='sales_record_rm_name_total_brk_idx',
        ),
        migrations.RenameIndex(
            model_name='salesrecord',
            new_name='sales_recor_client__c821d9_idx',
            old_name='sales_record_client_rm_idx',
        ),
        migrations.RenameIndex(
            model_name='salesrecord',
            new_name='sales_recor_period_534cdc_idx',
            old_name='sales_record_period_source_idx',
        ),
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='user_profil_wire_co_5cb1c8_idx',
            old_name='user_profile_wire_code_idx',
        ),
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='user_profil_role_c7e6f1_idx',
            old_name='user_profile_role_idx',
        ),
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='user_profil_reporti_5ca4a2_idx',
            old_name='user_profile_reporting_to_idx',
        ),
        migrations.AlterField(
            model_name='client',
            name='client_code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='wire_code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['email'], name='employee_di_email_cfcafc_idx'),
        ),
        migrations.AlterModelTable(
            name='salesrecord',
            table='sales_record',
        ),
    ]
