# Generated by Django 6.0.3 on 2026-04-05 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_fix_userprofile_employee_foreign_key'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='client',
            name='client_dime_wire_co_bf3abe_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='employee_di_manager_49e3d9_idx',
        ),
        migrations.AddField(
            model_name='client',
            name='employee',
            field=models.ForeignKey(blank=True, db_column='employee_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='core.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='manager_id',
            field=models.ForeignKey(blank=True, db_column='manager_id', help_text='Manager this employee reports to (self-join hierarchy via numeric ID)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='core.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='wire_code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['employee'], name='client_dime_employe_5793b8_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['manager_id'], name='employee_di_manager_49e3d9_idx'),
        ),
        migrations.RemoveField(
            model_name='client',
            name='wire_code',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='manager',
        ),
    ]
