# Generated by Django 5.2.7 on 2025-10-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
